---
- name: Upgrade packages
  become: yes 
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add repo for nodesource
  apt_repository:
   repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' 
   update_cache: yes

- name: install nodejs
  apt: name=nodejs

- name: Install PM2
  npm:
   name: pm2
   global: yes
