---
- name: Upgrade packages
  become: yes 
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Packages
  apt: name=npm update_cache=yes state=latest

- name: Install PM2
  npm: name=pm2 global=yes
