---
- name: Create backend directory
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: '775'

- name: Copy tar file from host to remote ubuntu home
  copy:
    owner: ubuntu
    mode: '644'
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Untar backend.tar.gz
  unarchive:
    owner: ubuntu
    src: /home/ubuntu/backend.tar.gz
    dest: /home/ubuntu/backend
    remote_src: yes

- name: Stop previously running pm2 backend
  become: yes
  become_user: ubuntu
  changed_when: false
  ignore_errors: yes  
  command: pm2 stop backend-service

- name: Start pm2 for backend
  become: yes
  become_user: ubuntu
  changed_when: false
  command: pm2 start --name backend-service npm -- start
  args:
    chdir: /home/ubuntu/backend
