---
- name: Upgrade packages
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Untar backend
  shell: tar -xf /home/ubuntu/backend.tar.gz 

- name: Stop pm2 service
  become: yes
  become_user: ubuntu
  ignore_errors: yes
  shell: pm2 stop backend

- name: Start pm2 service
  command: pm2 start backend
  args:
    chdir: /home/ubuntu
