version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: frontend/node-modules
          key: frontend-nodemodules
      - save_cache:
          paths: frontend/dist
          key: forntend-built-dist

  build-backend:
      docker: 
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Building backend artifacts from the source code
            command: |
              cd backend
              npm install
              ls -lrt *



workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
